version: "3.7"

services:
  rootgen:
    image: "ghcr.io/${CONTAINER_REG_USER}/${CONTAINER_REG_NAME}:latest"
    container_name: "rootsim"
    restart: "no"  # Changed from 'unless-stopped' to 'no'
    stop_grace_period: 10s
    env_file: .env
    mem_limit: 6g
    mem_reservation: 2g
    volumes:
      - .:/usr/src/app
    command: conda run -n rootSim python ./root_gen_bayesian.py
    # command: conda run -n rootSim python ./root_gen.py --from_config 1
    # command: conda run -n rootSim python ./root_gen.py