version: "3.7"

services:
  rootgen:
    image: "ghcr.io/${CONTAINER_REG_USER}/${CONTAINER_REG_NAME}:latest"
    container_name: "rootsim"
    restart: "no"  # Changed from 'unless-stopped' to 'no'
    stop_grace_period: 10s
    env_file: .env
    mem_limit: 6g
    mem_reservation: 2g
    volumes:
      - .:/usr/src/app
    # command: >
    #   /bin/bash -c "source activate rootSim &&
    #   python ./root_gen_optimise.py --n_trials 1 --stats_file 'data/summary_stats/root_stats_1.csv' &&
    #   cp data/optimise/root_optimise.csv data/optimise/root_optimise_res.csv &&
    #   python ./root_gen.py --from_config 1 --dir 'data/optimise' &&
    #   conda deactivate"  
    # command: conda run -n rootSim python ./generate_summary_stats.py
    # command: conda run -n rootSim python ./root_gen_optimise.py --n_trials 1 --stats_file "data/summary_stats/root_stats_1.csv"
    # command: conda run -n rootSim python ./root_gen.py --from_config 1
    command: conda run -n rootSim python ./plot_root.py --dir "data/optimise" --input "root_optimise.csv" # not displayed