# Use a smaller base image
FROM python:3.9-slim

# Set working directory
WORKDIR /usr/src/app

# Install necessary packages (combine into one RUN command to reduce layers)
RUN apt-get update && \
    apt-get install -y gcc libffi-dev libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/downloaded_packages

# Copy only necessary files
COPY requirements.txt ./

# Install Python dependencies
# First, install pyperclip without enforcing binary distribution
RUN pip install numpy==1.19.5 pyperclip==1.8.2 theano-pymc==1.1.2 pymc3==3.11.2 && \
    pip install --no-cache-dir -r requirements.txt

# Then, install the rest of the requirements, potentially using wheels
RUN pip install --no-cache-dir -r requirements.txt

# Further steps for your application...
